services:

  mysql:
    env_file:
      - ../../../.env
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DATABASE_USERNAME}", "-p${DATABASE_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    extends:
      file: common-config.yaml
      service: network-configuration

  fitverse-backend:
    env_file:
      - ../../../.env
    image: "rupesh1997/fitverse-backend:1.0.1"
    container_name: fitverse-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: "fit-verse-backend"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:mysql://mysql:3306/${DATABASE_NAME}?createDatabaseIfNotExist=true
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
    extends:
      file: common-config.yaml
      service: network-configuration

  fitverse-frontend:
    image: "rupesh1997/fitverse-frontend:1.0.0"
    container_name: fitverse-frontend
    depends_on:
      fitverse-backend:
        condition: service_started
    ports:
      - "4200:8080"
    extends:
      file: common-config.yaml
      service: network-configuration

networks:
  fitverse-network:
    driver: bridge
volumes:
  mysql-data:
