apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-backend
    version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
    - port: 8181
      targetPort: 8181
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Chart.Name }}-backend
