apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-my-cnf
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-mysql
data:
  my.cnf: |
    [mysqld]
    max_connections=200
    max_allowed_packet=256M
    default-storage-engine=InnoDB
    innodb_buffer_pool_size=512M
    innodb_log_file_size=256M
    slow_query_log=1
    slow_query_log_file=/var/log/mysql/slow-query.log
    long_query_time=2
