{{- if .Values.createSharedResources }}
# 1. Default deny all ingress traffic (Shared Resource)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-default-deny
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# 2. Allow backend to database (Shared Resource)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-backend-to-db
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}-mysql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Chart.Name }}-backend
      ports:
        - protocol: TCP
          port: {{ .Values.mysql.service.port }}
{{- end }}

---

# 3. Allow frontend to backend (Only if Backend is active)
{{- if .Values.backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-frontend-to-backend
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Chart.Name }}-frontend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.containerPort }}
{{- end }}

---

# 4. Allow ingress-nginx to frontend (Only if Frontend is active)
{{- if .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-ingress-frontend
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.containerPort }}
{{- end }}