apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-backend-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-frontend-pdb
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
