apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.environment.MYSQL_ROOT_PASSWORD | b64enc }}
  JASYPT_ENCRYPTOR_PASSWORD: {{ .Values.encryption.jasyptPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-image-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.imagePullSecret | b64enc }}
