replicaCount: 1
name: mysql
namespace: fitverse

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "fitverse"
imagePullSecrets: [ ] # secrets for pulling an image from a private repository

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 80

