services:
  fit-verse-backend:
    image: "rupesh1997/fit-verse-backend:1.0.0"
    container_name: fit-verse-backend
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: "fit-verse-backend"
    extends:
      file: common-config.yaml
      service: network-configuration
  fit-verse-frontend:
    image: "rupesh1997/fit-verse-frontend:1.0.0"
    container_name: fit-verse-frontend
    depends_on:
      fit-verse-backend:
        condition: service_started
    ports:
      - "8080:8080"
    extends:
      file: common-config.yaml
      service: network-configuration
networks:
  fit-verse-network:
    driver: bridge
