services:

  fitverse-backend:
    image: "rupesh1997/fitverse-backend:1.0.1"
    container_name: fitverse-backend
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: "fit-verse-backend"
    extends:
      file: common-config.yaml
      service: network-configuration

  fitverse-frontend:
    image: "rupesh1997/fitverse-frontend:1.0.0"
    container_name: fitverse-frontend
    depends_on:
      fitverse-backend:
        condition: service_started
    ports:
      - "8080:8080"
    extends:
      file: common-config.yaml
      service: network-configuration
networks:
  fitverse-network:
    driver: bridge
