apiVersion: v1
kind: Service
metadata:
  name: fitverse-backend
  namespace: fitverse
spec:
  selector:
    app: fitverse-backend
  ports:
    - port: 8181
      targetPort: 8181
      protocol: TCP
  type: LoadBalancer
