apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitverse-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "192.168.1.70"
      http:
        paths:
          - path: /api/v1.0.0/fit-verse
            pathType: Prefix
            backend:
              service:
                name: fitverse-backend
                port:
                  number: 8181
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fitverse-frontend
                port:
                  number: 4200
