apiVersion: v1
kind: Secret
metadata:
  name: fitverse-secrets
  namespace: fitverse
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bXktc2VjcmV0LXB3
  JASYPT_ENCRYPTOR_PASSWORD: bWFzdGVyLWtleS1oZXJl