replicaCount: 1
serviceName: fitverse-backend
namespace: fitverse

environment:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/fitverse?createDatabaseIfNotExist=true"
  SPRING_PROFILES_ACTIVE: "production"
  DATABASE_NAME: "fitverse"
  APPLICATION_CORS_ORIGINS: "http://192.168.1.70:4200"
  SPRING_DATASOURCE_PASSWORD: "root"

image:
  repository: rupesh1997/fitverse-backend
  pullPolicy: IfNotPresent
  tag: "1.0.1"

service:
  type: LoadBalancer
  port: 8181
  targetPort: 8181

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "500m"

